* Tervetuloa komentoriviharjoitukseen!
Tässä harjoituksessa opetellaan muutama peruskomento, joita
käyttämällä pääsee jo alkuun komentorivin käytössä. 

Opitaan: 
- ~pwd~ (print working directory), jolla voi tarkastaa nykyisen työskentelykansion sijainnin. 
- ~ls~ (list), joka antaa listan kansiossa olevista tiedostoista ja kansioista.
- ~cd~ (change directory), jonka avulla voit siirtyä kansiosta toiseen.
- ~mkdir~ (make directory), jolla voit luoda uuden kansion.
- ~echo~ tai ~write~, joilla voit kirjoittaa tekstiä tiedostoon.

Jotta pääset alkuun, sinun tulee siirtyä komentoriville. Avaa
komentorivi Windowsin valikosta etsimällä sovellus, nimeltä ~Windows PowerShell~. 
Voit kirjoittaa tuon Windowsin hakuun ja avata sovelluksen sieltä.

** Tarkasta työskentelykansio
Seuraava komento kertoo mikä on työskentelykansiosi. Minulla se on
omalla koneellani ~C:\Users\O-P~.
#+begin_src
pwd
#+end_src

** Listaa kansiossa olevat tiedostot
Seuraavaksi voit katsoa ~ls~ komennolla, mitä tiedostoja ja kansioita
työskentelykansiossasi on.
#+begin_src
ls
#+end_src

** Siirry "Tiedostot" -kansioon (PowerShellissä My Documents)
Voit siirtyä käyttämällä ~cd~ komentoa. Jos esimerkiksi olisin ~Users~
-kansiossa, voisin siirtyä ~O-P~ -kansioon komennolla ~cd O-P~.

Huomaa, että siirtyessäsi kansioon, jonka nimi sisältää välilyöntejä,
sinun tulee kirjoittaa se lainausmerkkien tai heittomerkkien sisään:
"~My Documents~" tai '~My Documents~'. 

*PRO TIP:* Painamalla sarkainta (TAB) saat komentorivin täydentämään
kirjoitustasi. Voit kirjoittaa alun jonkin kansion nimestä ja painaa
TAB, jonka jälkeen komentorivi täydentää nimen tai antaa vaihtoehdot
näkyviin.
#+begin_src
cd tähän-kansion-nimi
#+end_src

Jos haluat siirtyä yhden kansion takaisinpäin, voit laittaa kaksi
pistettä komennon perään, välilyönnillä erotettuna.
#+begin_src
cd ..
#+end_src

** Luo kansio "Tiedostot" -kansion sisälle
Voit nyt vielä tarkistaa, että olethan varmasti ~Tiedostot~ -kansiossa
(englanniksi se on Windowsissa My Documents).

Sitten voit luoda kansion antamalla seuraavan komennon:
#+begin_src
mkdir hacked
#+end_src

** Luo tiedosto "hacked" -kansioon
Siirry ~hacked~ -kansioon. Käytä alla olevaa komentoa tiedoston luomiseen. 

OLE HUOLELLINEN! Jos kirjoitat ~>>~ -komennon sijasta ~>~, tiedosto
ylikirjoitetaan! tai jos kirjoitat vahingossa väärän tiedoston nimen,
teksti menee väärään tiedostoon.

#+begin_src
echo "Tämä tiedosto täysin hacked" >> hack.txt
#+end_src

* Tehtävä suoritettu!
Nyt sinulla pitäisi olla omien kansioidesi joukossa ~hacked~ -niminen
kansio ja sen sisällä tiedosto ~hack.txt~. Hienoa!
